# Generated by Django 5.2.1 on 2025-06-02 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bed_number', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=50)),
                ('room_status', models.CharField(max_length=10)),
                ('issue_type', models.CharField(choices=[('cleanliness', 'Cleanliness'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('submitted_by', models.CharField(default='Patient', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('assigned_department', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=20)),
                ('Block', models.CharField(max_length=10)),
                ('Floor_no', models.IntegerField()),
                ('ward', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
