# Generated by Django 5.0.2 on 2025-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_id_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='qr_code_id',
        ),
        migrations.AddField(
            model_name='room',
            name='dataenc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
