# Generated by Django 5.2.1 on 2025-06-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
    ]
