# Generated by Django 5.2.1 on 2025-06-11 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_Category',
            fields=[
                ('issueCategoryCode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('issueCategoryname', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_categories', to='complaints.department')),
            ],
        ),
    ]
