# Generated by Django 5.2.1 on 2025-06-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_rename_dept_code_department_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
