# Generated by Django 5.2.1 on 2025-06-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_department_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_category',
            name='issue_category_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
